"""Export, diff and import n8n workflows as reviewable files in git.

Most self-hosted n8n state exists only inside a running container: it is edited
in a browser, never reviewed, and lost with the volume. This module makes the
repository the source of truth, so a workflow change arrives as a pull request
with a readable diff and lands through the pipeline like any other code.

Two properties make the diff readable rather than merely present. Read-only
fields are stripped before writing, because `updatedAt` and `versionId` change
on every save and would bury the real edit. And every object is serialised with
sorted keys, so a field the editor happens to emit in a different order does not
show up as a change.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

from opsagent.n8n.client import REQUIRED_FIELDS, WRITABLE_FIELDS, JsonDict, N8nClient

MANIFEST_NAME = "manifest.yaml"
MANIFEST_HEADER = (
    "# Generated by `opsagent n8n export`. Maps instance workflow ids to files.\n"
    "# Edit the workflow JSON, not this file. Ids are absent until first import.\n"
)

_SLUG_SEPARATORS = re.compile(r"[^a-z0-9]+")


class SyncError(RuntimeError):
    """A local problem with the workflow directory rather than an API failure."""


def slugify(name: str) -> str:
    """Turn a workflow name into a stable file stem."""
    slug = _SLUG_SEPARATORS.sub("-", name.strip().lower()).strip("-")
    if not slug:
        raise SyncError(f"workflow name {name!r} produces an empty file name")
    return slug


def to_committed_payload(workflow: JsonDict) -> JsonDict:
    """Reduce an API workflow object to the fields that belong in git.

    Raises:
        SyncError: A field the create schema requires is missing, which would
            turn into a 400 at import time rather than here.
    """
    missing = REQUIRED_FIELDS - workflow.keys()
    if missing:
        name = workflow.get("name", "<unnamed>")
        raise SyncError(f"workflow {name!r} is missing required fields: {sorted(missing)}")
    return {key: value for key, value in workflow.items() if key in WRITABLE_FIELDS}


def render_workflow_file(payload: JsonDict) -> str:
    """Serialise deterministically, so an unchanged workflow produces no diff."""
    return json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


@dataclass(frozen=True, slots=True)
class ManifestEntry:
    """One workflow: where it lives in git, and what it is in the instance."""

    file: str
    name: str
    active: bool
    # Absent until the workflow has been imported at least once, which is the
    # normal state for a workflow authored in git and never yet deployed.
    id: str | None = None


@dataclass(frozen=True, slots=True)
class Manifest:
    entries: tuple[ManifestEntry, ...] = ()

    def by_file(self) -> dict[str, ManifestEntry]:
        return {entry.file: entry for entry in self.entries}


@dataclass(frozen=True, slots=True)
class WorkflowDiff:
    """What differs between the instance and the repository."""

    only_in_instance: tuple[str, ...] = ()
    only_in_git: tuple[str, ...] = ()
    changed: tuple[str, ...] = ()

    @property
    def is_empty(self) -> bool:
        return not (self.only_in_instance or self.only_in_git or self.changed)


@dataclass(frozen=True, slots=True)
class ImportResult:
    created: tuple[str, ...] = ()
    updated: tuple[str, ...] = ()
    activated: tuple[str, ...] = ()
    deactivated: tuple[str, ...] = ()
    unchanged: tuple[str, ...] = ()


@dataclass
class ExportResult:
    written: list[str] = field(default_factory=list)
    manifest: Manifest = field(default_factory=Manifest)


def load_manifest(directory: Path) -> Manifest:
    """Read the manifest, treating a missing file as an empty repository."""
    path = directory / MANIFEST_NAME
    if not path.exists():
        return Manifest()

    raw: Any = yaml.safe_load(path.read_text(encoding="utf-8"))
    if raw is None:
        return Manifest()
    if not isinstance(raw, dict) or "workflows" not in raw:
        raise SyncError(f"{path} is not a workflow manifest")

    entries = []
    for item in raw["workflows"]:
        entries.append(
            ManifestEntry(
                file=str(item["file"]),
                name=str(item["name"]),
                active=bool(item.get("active", False)),
                id=str(item["id"]) if item.get("id") else None,
            )
        )
    return Manifest(entries=tuple(entries))


def write_manifest(directory: Path, manifest: Manifest) -> None:
    payload = {
        "workflows": [
            {
                "file": entry.file,
                "name": entry.name,
                "active": entry.active,
                **({"id": entry.id} if entry.id else {}),
            }
            for entry in sorted(manifest.entries, key=lambda entry: entry.file)
        ]
    }
    body = yaml.safe_dump(payload, sort_keys=False, default_flow_style=False, allow_unicode=True)
    (directory / MANIFEST_NAME).write_text(MANIFEST_HEADER + body, encoding="utf-8")


def read_workflow_file(directory: Path, file_name: str) -> JsonDict:
    path = directory / file_name
    if not path.exists():
        raise SyncError(f"{path} is listed in the manifest but does not exist")
    decoded: JsonDict = json.loads(path.read_text(encoding="utf-8"))
    return decoded


def validate_directory(directory: Path) -> list[str]:
    """Check the committed workflows without contacting an instance.

    This is the CI gate. It runs on a pull request, where there is no cluster
    and no API key, and it catches the mistakes that would otherwise surface as
    a 400 during a deploy: a hand-edited file that kept a read-only field, a
    workflow missing a required one, or a manifest that has drifted from the
    files beside it.

    Returns:
        Human-readable problems, empty when the directory is sound.
    """
    problems: list[str] = []
    manifest = load_manifest(directory)
    listed = {entry.file for entry in manifest.entries}
    on_disk = {path.name for path in directory.glob("*.json")}

    problems.extend(
        f"{name} is in the manifest but not on disk" for name in sorted(listed - on_disk)
    )
    problems.extend(
        f"{name} is on disk but not in the manifest" for name in sorted(on_disk - listed)
    )

    for entry in sorted(manifest.entries, key=lambda item: item.file):
        if entry.file not in on_disk:
            continue
        raw = (directory / entry.file).read_text(encoding="utf-8")
        try:
            parsed = json.loads(raw)
        except json.JSONDecodeError as error:
            problems.append(f"{entry.file} is not valid JSON: {error}")
            continue
        try:
            payload = to_committed_payload(parsed)
        except SyncError as error:
            problems.append(f"{entry.file}: {error}")
            continue
        if str(parsed.get("name", "")) != entry.name:
            problems.append(
                f"{entry.file} is named {parsed.get('name')!r}, manifest says {entry.name!r}"
            )
        # Canonical form also catches read-only fields: they are stripped by
        # to_committed_payload, so a file that kept one no longer round-trips.
        if raw != render_workflow_file(payload):
            problems.append(
                f"{entry.file} is not in canonical form; re-run `opsagent n8n export` "
                "rather than hand-editing, or the import will be rejected"
            )

    return problems


async def export_workflows(client: N8nClient, directory: Path) -> ExportResult:
    """Write every workflow in the instance to `directory` and rebuild the manifest."""
    directory.mkdir(parents=True, exist_ok=True)
    workflows = await client.list_workflows()

    result = ExportResult()
    entries: list[ManifestEntry] = []
    seen: dict[str, str] = {}

    for workflow in sorted(workflows, key=lambda item: str(item.get("name", ""))):
        name = str(workflow["name"])
        file_name = f"{slugify(name)}.json"
        if file_name in seen:
            raise SyncError(
                f"workflows {seen[file_name]!r} and {name!r} both map to {file_name}; "
                "rename one of them in n8n"
            )
        seen[file_name] = name

        (directory / file_name).write_text(
            render_workflow_file(to_committed_payload(workflow)), encoding="utf-8"
        )
        result.written.append(file_name)
        entries.append(
            ManifestEntry(
                file=file_name,
                name=name,
                active=bool(workflow.get("active", False)),
                id=str(workflow["id"]) if workflow.get("id") else None,
            )
        )

    result.manifest = Manifest(entries=tuple(entries))
    write_manifest(directory, result.manifest)
    return result


async def diff_workflows(client: N8nClient, directory: Path) -> WorkflowDiff:
    """Compare the instance against the repository without changing either.

    This is what CI runs to prove the round trip is clean, and what a human runs
    before an export to see whether the instance drifted.
    """
    manifest = load_manifest(directory)
    instance = {str(item["name"]): item for item in await client.list_workflows()}

    only_in_git: list[str] = []
    changed: list[str] = []

    for entry in manifest.entries:
        committed = to_committed_payload(read_workflow_file(directory, entry.file))
        live = instance.pop(entry.name, None)
        if live is None:
            only_in_git.append(entry.name)
            continue
        content_drifted = to_committed_payload(live) != committed
        # Activation counts as drift too: a workflow that is enabled in git and
        # disabled in the instance is not "in sync" just because the JSON matches.
        activation_drifted = bool(live.get("active", False)) != entry.active
        if content_drifted or activation_drifted:
            changed.append(entry.name)

    return WorkflowDiff(
        only_in_instance=tuple(sorted(instance)),
        only_in_git=tuple(sorted(only_in_git)),
        changed=tuple(sorted(changed)),
    )


async def import_workflows(client: N8nClient, directory: Path) -> ImportResult:
    """Push the repository to the instance and reconcile activation state.

    Workflows present in the instance but absent from git are left alone rather
    than deleted. Reconciliation that can delete is a much bigger promise than
    this pipeline needs, and `diff` already reports them.
    """
    manifest = load_manifest(directory)
    live_by_name = {str(item["name"]): item for item in await client.list_workflows()}

    created: list[str] = []
    updated: list[str] = []
    activated: list[str] = []
    deactivated: list[str] = []
    unchanged: list[str] = []
    new_entries: list[ManifestEntry] = []

    for entry in manifest.entries:
        payload = to_committed_payload(read_workflow_file(directory, entry.file))
        live = live_by_name.get(entry.name)
        workflow_id = entry.id or (str(live["id"]) if live and live.get("id") else None)

        if workflow_id is None:
            response = await client.create_workflow(payload)
            workflow_id = str(response["id"])
            created.append(entry.name)
            was_active = False
        elif live is not None and to_committed_payload(live) == payload:
            unchanged.append(entry.name)
            was_active = bool(live.get("active", False))
        else:
            await client.update_workflow(workflow_id, payload)
            updated.append(entry.name)
            was_active = bool(live.get("active", False)) if live else False

        # `active` is read-only in the schema, so activation is a separate call
        # rather than a field in the payload.
        if entry.active and not was_active:
            await client.activate_workflow(workflow_id)
            activated.append(entry.name)
        elif not entry.active and was_active:
            await client.deactivate_workflow(workflow_id)
            deactivated.append(entry.name)

        new_entries.append(
            ManifestEntry(file=entry.file, name=entry.name, active=entry.active, id=workflow_id)
        )

    # Ids assigned on first import are written back so the next run updates in
    # place instead of creating a duplicate.
    write_manifest(directory, Manifest(entries=tuple(new_entries)))

    return ImportResult(
        created=tuple(created),
        updated=tuple(updated),
        activated=tuple(activated),
        deactivated=tuple(deactivated),
        unchanged=tuple(unchanged),
    )
